repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -w .
        language: system
        files: \.go$
      - id: test
        name: test
        entry: go test -v -p=1 ./...
        pass_filenames: false
        types: [go]
        language: system